const fruitList = [
    'Acai', 
    'Aceola',
    'Apple',
    'Apricots',
    'Avocado',
    'Banana',
    'Blackberry',
    'Blueberries',
    'Camu Camu berry',
    'Cherries',
    'Coconut',
    'Cranberry',
    'Cucumber',
    'Currents',
    'Dates',
    'Durian',
    'Fig',
    'Goji berries',
    'Gooseberry',
    'Grapefruit',
    'Grapes',
    'Jackfruit',
    'Kiwi',
    'Kumquat',
    'Lemon',
    'Lime',
    'Lucuma',
    'Lychee',
    'Mango',
    'Mangosteen',
    'Melon',
    'Mulberry',
    'Nectarine',
    'Orange',
    'Papaya',
    'Passion Fruit',
    'Peach',
    'Pear',
    'Pineapple',
    'Plum',
    'Pomegranate',
    'Pomelo',
    'Prickly Pear',
    'Prunes',
    'Raspberries',
    'Strawberries',
    'Tangerine/Clementine',
    'Watermelon'
  ]
  
  export default fruitList